eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webmvc:
         routes:
          - id: emp-backend
            uri: lb://emp-service
            predicates:
             Path=/emp/**
            filters:
             - name: CircuitBreaker
               args:
                 id: cb2
                 name: apig-cb
                 fallback-uri: forward:/emp-service-fallback
          - id: hr-backend
            uri: lb://hr-service
            predicates:
              Path=/hr/**
          - id: test-uri
            uri: http://www.google.co.in
            predicates: 
              Path=/test/**

resilience4j.circuitbreaker:
 instances:
   apig-cb:
    registerHealthIndicator: true
    slidingWindowSize: 10
    permittedNumberOfCallsInHalfOpenState: 3
    slidingWindowType: COUNT_BASED
    minimumNumberOfCalls: 5
    waitDurationInOpenState: 5s
    failureRateThreshold: 33.3
    automaticTransitionFromOpenToHalfOpenEnabled: true


management:
 endpoints:
   web:
    exposure:
      include: "*"
 endpoint:
    health:
     show-details: always
 health:
    circuitbreakers:
      enabled: true