spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.mariadb.jdbc.Driver}
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:springdb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/